#!/usr/bin/env sh

xsetroot -cursor_name left_ptr &
hsetroot -solid "#1d1f21" &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x dunst > /dev/null || dunst &
pgrep -x light-locker > /dev/null || light-locker &
pgrep -x picom > /dev/null || picom &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width                0
bspc config window_gap                  6
bspc config top_padding                 0

bspc config split_ratio                 0.5
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       false

bspc config focused_border_color        "#555555"
bspc config active_border_color         "#dddddd"
bspc config normal_border_color         "#1d1f21"
bspc config presel_feedback_color       "#373b41"

bspc rule -a feh                        state=floating
bspc rule -a Zathura                    state=tiled
bspc rule -a Google-chrome              state=fullscreen
bspc rule -a Matplotlib                 state=floating
