#!/usr/bin/env sh

# set pointer
xsetroot -cursor_name left_ptr &

# set wallpaper
~/bin/wallset.sh "$(cat $HOME/Pictures/wallpapers/current)"

# merge Xresources
xrdb ~/.Xresources &

# map capslock to escape
setxkbmap -option caps:escape &

# hotkey daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# touchpad gestures
libinput-gestures-setup restart &

# notification daemon
pgrep -x dunst > /dev/null || dunst &

# compositor
pgrep -x picom > /dev/null || picom --daemon

# urxvt daemon
pgrep -x urxvtd > /dev/null || urxvtd -q -o -f

# lemonbar
killall panel; setsid ~/bin/panel &

# borders
killall borders.sh; setsid ~/bin/borders.sh &

# bspc monitor -d α β γ δ ε ζ η θ ι
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width                2
bspc config window_gap                  6

bspc config split_ratio                 0.5
bspc config borderless_monocle          true
bspc config gapless_monocle             false
bspc config focus_follows_pointer       false

bspc config focused_border_color        "#2a2f35"
bspc config active_border_color         "#dddddd"
bspc config normal_border_color         "#1d1f21"
bspc config presel_feedback_color       "#373b41"

bspc rule -a feh                        state=floating
bspc rule -a Zathura                    state=tiled
bspc rule -a Thunar                     state=floating
bspc rule -a matplotlib                 state=floating
